version: '3'
services:
  mongo:
    image: mongo:3.6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./volume/mongo/:/data/db
    networks:
      - baas-challenge
  localstack:
    image: localstack/localstack
    ports:
      - "4567-4584:4567-4584"
      - "8055:8080"
    environment:
      - SERVICES=s3
      - DEBUG=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - baas-challenge
networks:
    baas-challenge:
      driver: bridge