version: '3'
services:
  mongo:
    image: mongo:3.6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./volume/mongo/:/data/db
    networks:
      - baas-challenge
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_ACCESS_KEY_ID=ACCESSKEYAWSUSER
      - AWS_SECRET_ACCESS_KEY=sEcreTKey
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_DEFAULT_OUTPUT=json
      - HOSTNAME_EXTERNAL=localhost
      - USE_SSL=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - baas-challenge
networks:
    baas-challenge:
      driver: bridge